### ISSUE TITLE
can not get libboost_serialization.dylib after use this tool

### ISSUE THREAD

**Issue by ljlin** [danoli3/ofxiOSBoost#13]
Can only get boost.a , but i also need libboost_serialization.dylib. How should I deal with that. Thanks :P

**Comment by danoli3** [comment]
```Boost.a``` is a static 'fat' lib rather than a dylib.

If you want a .dylib you will need to rather than ```ar -x``` ing the object files, you do something like this instead:
Use ```llvm -dynamiclib -undefined suppress -flat_namespace *.o -o something.dylib```

This is currently not supported by this repo though. If this comes up more I'll think about adding another script for it (feel free to PR on here with a working one).
